jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Build package
      run: yarn prepack
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Lint files
      run: yarn lint
    - continue-on-error: true
      name: Typecheck files
      run: yarn typecheck
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup
      uses: ./.github/actions/setup
    - continue-on-error: true
      name: Run unit tests
      run: yarn test --maxWorkers=2 --coverage
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
